### PR TITLE
Remove JSON_PRETTY_PRINT

### PR DESCRIPTION
**Pull request by kimegede**
Saving JSON with pretty print, will just use extra bytes.

### CODE REVIEW

**Comment by kitsunet** [comment]
Hey thanks for your first constribution. I generally like the idea of getting rid of that, but I am not sure if that might break things somewhere, if we rely on the DB being PRETTY (sounds weird, but I have some code in mind in Neos, will check that).

**Comment by kimegede** [comment]
Sounds perfect @kitsunet, it could also be changed to a setting.
Eg. `development` context could be default `JSON_PRETTY_PRINT` and `production` context could be without.
Hope it's not to be a breaking change.

**Comment by kimegede** [comment]
@kitsunet Just saw this is a sub, should I make a PR to https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Persistence/Doctrine/DataTypes/JsonArrayType.php#L134 instead?

**Comment by kdambekalns** [comment]
Yes, please open a PR on the development collection… Thanks!

**Comment by kimegede** [comment]
Created and linked above ^^

**Pull request closed without merging**
