### PR TITLE
Fix kickstart command

### PR DESCRIPTION
**Pull request by victormartinez**
This PR aims to fix a problem pointed out by @kitsunet in PR (https://github.com/neos/flow/pull/5). Hope that is ok now. I'm looking forward to contribute to this project.

### CODE REVIEW

**Comment by bwaidelich** [comment]
Looks good to me, but shouldn't this go to the 3.0 branch?

**Comment by victormartinez** [comment]
I think I didn't get the workflow. Shouldn't it go to the most recent branch (3.3) @bwaidelich? Could explain me the workflow?

**Comment by kdambekalns** [comment]
Thanks for the contribution!

It should go into the lowest affected branch, bugfixes are upmerged from there.

But more important: it must be against the neos/flow-development-collection. **This package is a read-only subsplit**.

**Comment by bwaidelich** [comment]
@victormartinez sorry for the superficial comment and late reaction. As Karsten wrote, this repository is [read-only](https://github.com/neos/flow/blob/master/Readme.rst) and PRs should go against the [dev-collection](https://github.com/neos/flow-development-collection).
You'll find contribution gudelines on [discuss.neos.io](https://discuss.neos.io/t/code-contribution-guideline/503)

**Pull request closed without merging**
